// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workpdf-airy/AiryMinimal.tsx": () => import("../components/mockups/workpdf-airy/AiryMinimal.tsx"),
  "./components/mockups/workpdf-compact/CompactGrid.tsx": () => import("../components/mockups/workpdf-compact/CompactGrid.tsx"),
  "./components/mockups/workpdf-convert/ConvertPage.tsx": () => import("../components/mockups/workpdf-convert/ConvertPage.tsx"),
  "./components/mockups/workpdf-settings/SettingsPage.tsx": () => import("../components/mockups/workpdf-settings/SettingsPage.tsx"),
  "./components/mockups/workpdf-sidebar/CompactGrid.tsx": () => import("../components/mockups/workpdf-sidebar/CompactGrid.tsx")
};
